language: node_js
node_js:
  - node
before_script:
  - npm install
script:
  - npm run build
after_success:
  - npm run deploy
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - bower_components
